%
%  Grad-Shafranov equilibrium codes (Welander)
%
%  gseq - return equilibrium for a state vector x, defined by gsconfig
%  gspert - return linear response of equilibrium to perturbations
%  gsdesign - design Grad-Shafranov equilibrium
%  gsupdate - update an equilibrium including profiles, response, dynamics
%  gsprofiles - return large selection of profiles for an equilibrium
%
%  For setting up Simulink module GSevolve:
%  gsconfig - creates configuration data for gsupdate, used by GSevolve
%  gsinit - creates initial equilibrium for gsupdate, used by GSevolve
%
%  Miscellaneous:
%  gsdesign_recreate_init - find spec, config such that: init = gsdesign(spec,init,config)
%  gsdesignold - old version of gsdesign
%  gscontour22 - Find closed contour given a point on the contour
%  gsboundary - find plasma boundary given the flux on the grid
%  gstouches - find points on limiter that the plasma possibly touches
%  gsnulls - find nulls in the flux on the grid (axes and x-points)
%  gsgamma - calculate vertical growth rate for an equilibrium
%  gscalc - calculate flux generated by current in plasma
 
% gsdesign_demo_d3d_DN.m
% gsdesign_demo_d3d_DSNF.m
% gsdesign_demo_east_DSNF.m
% gsdesign_demo_east_LSNF.m
% gsdesign_demo_iter.m
% gsdesign_demo_kstar_ISS.m
% gsdesign_iss.m
% gsdesignold.m
% -rw-r--r--  1 welander  19230 Oct  2 21:09 gsevolve_config.m
% -rw-r--r--  1 welander   7404 Oct  2 21:09 gsevolve_help.txt
% -rw-r--r--  1 welander   3804 Oct  2 21:09 gsevolve_init.m
% -rw-r--r--  1 welander   8133 Oct  2 21:09 gsevolve.m
% -rw-r--r--  1 welander  16471 Oct  2 21:09 gspertcalc.m
% -rw-r--r--  1 welander   4948 Oct  2 21:09 gspert_dpsizr.m
